# This is a summary of all the code for this tutorial
from coinbase.rest import RESTClient
from json import dumps
import math
import secret

api_key = secret.api_key
api_secret = secret.api_secret

client = RESTClient(api_key=api_key, api_secret=api_secret)

# ACCOUNT INFO
accounts = client.get_accounts()
print(dumps(accounts, indent=2))

# CURRENT PRICE
product = client.get_product("BTC-USD")
btc_usd_price = float(product["price"])
adjusted_btc_usd_price = str(math.floor(btc_usd_price - (btc_usd_price * 0.05)))
print(adjusted_btc_usd_price)


# Placing a Market Order
order = client.market_order_buy(
    client_order_id="020a4118-6c22-4915-ba88-25655d8fe1e4", # should be unique generated by user uuid
    product_id="BTC-USD",
        quote_size="1"
    )

order_id = order["order_id"]

fills = client.get_fills(order_id=order_id)
print(dumps(fills, indent=2))


# Placing an Order 5% Below Price
limit_order = client.limit_order_gtc_buy(
    client_order_id="00000002",
    product_id="BTC-USD",
    base_size="0.0002",
    limit_price=adjusted_btc_usd_price
)

limit_order_id = limit_order["order_id"]

# Cancelling the Order
client.cancel_orders(order_ids=[limit_order_id])